"""initial schema

Revision ID: a4c37fc0f199
Revises: 
Create Date: 2026-07-11 11:29:25.699772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4c37fc0f199'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fare_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_fare', sa.Float(), nullable=False),
    sa.Column('per_km_rate', sa.Float(), nullable=False),
    sa.Column('per_min_rate', sa.Float(), nullable=False),
    sa.Column('booking_fee', sa.Float(), nullable=False),
    sa.Column('minimum_fare', sa.Float(), nullable=False),
    sa.Column('per_kg_rate', sa.Float(), nullable=False),
    sa.Column('per_m3_rate', sa.Float(), nullable=False),
    sa.Column('pool_discount_pct', sa.Float(), nullable=False),
    sa.Column('peak_hour_multiplier', sa.Float(), nullable=False),
    sa.Column('night_multiplier', sa.Float(), nullable=False),
    sa.Column('surge_enabled', sa.Boolean(), nullable=False),
    sa.Column('surge_cap', sa.Float(), nullable=False),
    sa.Column('cancellation_fee', sa.Float(), nullable=False),
    sa.Column('cancellation_free_window_sec', sa.Integer(), nullable=False),
    sa.Column('peak_hours', sa.JSON(), nullable=False),
    sa.Column('night_hours', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='active', nullable=False),
    sa.Column('rating_avg', sa.Float(), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('driver_profiles',
    sa.Column('uid', sa.String(length=128), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=True),
    sa.Column('vehicle_model', sa.String(length=100), nullable=True),
    sa.Column('plate_number', sa.String(length=30), nullable=True),
    sa.Column('max_passengers', sa.Integer(), nullable=True),
    sa.Column('max_weight_kg', sa.Float(), nullable=True),
    sa.Column('max_volume_m3', sa.Float(), nullable=True),
    sa.Column('online_status', sa.String(length=20), server_default='offline', nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('geohash', sa.String(length=12), nullable=True),
    sa.Column('location_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rating_avg', sa.Float(), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_driver_profiles_geohash'), 'driver_profiles', ['geohash'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('passenger_id', sa.String(length=128), nullable=False),
    sa.Column('passenger_name', sa.String(length=200), nullable=True),
    sa.Column('driver_id', sa.String(length=128), nullable=True),
    sa.Column('driver_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=False),
    sa.Column('destination_lng', sa.Float(), nullable=False),
    sa.Column('destination_address', sa.Text(), nullable=True),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('route_path', sa.JSON(), nullable=False),
    sa.Column('fare_estimate', sa.Float(), nullable=False),
    sa.Column('fare_breakdown', sa.JSON(), nullable=False),
    sa.Column('goods_weight_kg', sa.Float(), server_default='0', nullable=False),
    sa.Column('goods_volume_m3', sa.Float(), server_default='0', nullable=False),
    sa.Column('goods_description', sa.String(length=200), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('schedule_broadcast_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('final_fare', sa.Float(), nullable=True),
    sa.Column('cancellation_fee', sa.Float(), nullable=True),
    sa.Column('cancel_reason', sa.String(length=300), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('rated_by_passenger', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('rated_by_driver', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['passenger_id'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_driver_id'), 'rides', ['driver_id'], unique=False)
    op.create_index(op.f('ix_rides_passenger_id'), 'rides', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_rides_requested_at'), 'rides', ['requested_at'], unique=False)
    op.create_index(op.f('ix_rides_schedule_broadcast_at'), 'rides', ['schedule_broadcast_at'], unique=False)
    op.create_index(op.f('ix_rides_status'), 'rides', ['status'], unique=False)
    op.create_table('ratings',
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_id', sa.String(length=128), nullable=True),
    sa.Column('driver_id', sa.String(length=128), nullable=True),
    sa.Column('by_passenger', sa.JSON(), nullable=True),
    sa.Column('by_driver', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('ride_id')
    )
    op.create_table('ride_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=128), nullable=False),
    sa.Column('sender_name', sa.String(length=200), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_messages_ride_id'), 'ride_messages', ['ride_id'], unique=False)
    op.create_table('ride_requests',
    sa.Column('ride_id', sa.String(length=36), nullable=False),
    sa.Column('passenger_name', sa.String(length=200), nullable=True),
    sa.Column('pickup', sa.JSON(), nullable=False),
    sa.Column('destination', sa.JSON(), nullable=False),
    sa.Column('goods', sa.JSON(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('fare_estimate', sa.Float(), nullable=False),
    sa.Column('geohash', sa.String(length=12), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('declined_by', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('ride_id')
    )
    op.create_index(op.f('ix_ride_requests_expires_at'), 'ride_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_ride_requests_geohash'), 'ride_requests', ['geohash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ride_requests_geohash'), table_name='ride_requests')
    op.drop_index(op.f('ix_ride_requests_expires_at'), table_name='ride_requests')
    op.drop_table('ride_requests')
    op.drop_index(op.f('ix_ride_messages_ride_id'), table_name='ride_messages')
    op.drop_table('ride_messages')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_rides_status'), table_name='rides')
    op.drop_index(op.f('ix_rides_schedule_broadcast_at'), table_name='rides')
    op.drop_index(op.f('ix_rides_requested_at'), table_name='rides')
    op.drop_index(op.f('ix_rides_passenger_id'), table_name='rides')
    op.drop_index(op.f('ix_rides_driver_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_driver_profiles_geohash'), table_name='driver_profiles')
    op.drop_table('driver_profiles')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    op.drop_table('fare_rules')
    # ### end Alembic commands ###
